version: '3'
services:
  neo4j:
    image: neo4j:3.5.1
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins
  
  graphql:
    build: graphql
    ports:
      - 4000:4000
    volumes:
      - ./graphql/dist:/app/dist
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: password
      FIREBASE_DATABASE_ENDPOINT: https://novels-a5884.firebaseio.com
    command: "node dist/main.js"